[build]
  command = "prisma generate && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--version"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_version = "18.17.0"
  external_node_modules = ["@prisma/client"]
