services:
  - type: web
    name: diet-tracker
    runtime: node
    plan: free
    buildCommand: npm install && prisma generate && npx prisma db push && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.18.1
      - key: DATABASE_URL
        sync: false
